name: Build Finely Installer

on:
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install flet pyinstaller

      - name: Build executable
        run: |
          flet pack main.py --name "Finely"

      - name: Rename output
        run: |
          if [[ '${{ matrix.platform }}' == 'windows-latest' ]]; then
            mv dist/Finely.exe dist/Finely-Windows.exe
          elif [[ '${{ matrix.platform }}' == 'macos-latest' ]]; then
            mv dist/Finely.app dist/Finely-macOS.app
          else
            mv dist/Finely dist/Finely-Linux.AppImage
          fi
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Finely-${{ matrix.platform }}
          path: dist/
